### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by ybpaopao** [mingbocui/Human-Motion-Prediction#1]
Hi, is this code an implement of Social-GAN? Have you successfully run Social-GAN and get the same results as reported in the CVPR PAPER? Thanks!

**Comment by mingbocui** [comment]
No, I this repo is just part of my semester project and it did not focus on the real word trajectory. Yeah, if you just use the hyperparameters provided by the author, the result will be very bad. You have to print the hyperparameters of a certain pre-trained model.
